language: node_js
node_js:
  - lts/*
dist: xenial
addons:
  chrome: stable
script:
  - npx lerna bootstrap
  - ls -l libs/picker/node_modules/@whee
  - npx lerna run test
after_success:
  - bash <(curl -s https://codecov.io/bash) -v